### ISSUE TITLE
Proposed SIG-Build meeting agenda for 21/OCT/2021 @ 02:00pm PT / 05:00pm ET

### ISSUE THREAD

**Issue by aFinchy** [o3de/sig-operations#17]
## Meeting Details

- **Date/Time:** 21/OCT/2021 @ 02:00pm PT / 05:00pm ET
- **Location:** [Discord SIG-Operations Voice Room](https://discord.gg/eqphBtXj)
- **Moderator:** TBA
- **Note Taker** Volunteers welcome!

The [SIG-Operations Meetings](https://github.com/o3de/sig-operations/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

- O3DECon

## Meeting Agenda

- Future meetings, time ranges, Frequency
- Public Assets for download, easy find
- Discord partner Application _(Discord Perks)_
- Youtube Channel Update _(URL)_
- Update on Branding Kit?
- SIG Charter as its mostly empty in this repro. This makes it hard to understand what is the ownership and responsibilities of sig-operations. Propose we start the process of updating sig-operations charter.
- Ownership of the o3de.org website and if sig-operations is responsible for any pieces. This is cross-cutting from sig-security about who is responsible for the security and frameworks used to host content.
- Process for RFC archiving, if a responsibility for sig-operations or a process for sig-operations to own (due to lack of charter unclear if operations is responsible SIG for this). Problem: most SIGs are archiving RFCs locally in their repros which makes discovery hard. RFCs are also not being archived consistently. What processes should we be following? What should we be doing with https://github.com/o3de/rfcs? What should be the communication policy when RFCs are published, moved to final comment and accepted by a SIG?
- Documentation search support
- robots.txt management
- Automation of Review and Merge management on github repos

- Community Art?

Action Items for SIG maintainers:

- Need to update issues templates for SIG. Meeting agenda template had SIG-BUILD as title. See https://github.com/o3de/sig-operations/blob/main/.github/ISSUE_TEMPLATE/Meeting-Agenda-Template.md and theres no standard maintainer promotion issue template ie https://github.com/o3de/sig-core/blob/main/.github/ISSUE_TEMPLATE/Reviewer_Maintainer_Nomination.md

Please comment on this for anything you would like added to the agenda!

**Comment by lmbr-pip** [comment]
Moving my comments from: https://github.com/o3de/sig-operations/issues/16 and closing that to avoid confusion.

Propose discussing:

- SIG Charter as its mostly empty in this repro. This makes it hard to understand what is the ownership and responsibilities of sig-operations. Propose we start the process of updating sig-operations charter.
- Ownership of the o3de.org website and if sig-operations is responsible for any pieces. This is cross-cutting from sig-security about who is responsible for the security and frameworks used to host content.
- Process for RFC archiving, if a responsibility for sig-operations or a process for sig-operations to own (due to lack of charter unclear if operations is responsible SIG for this). Problem: most SIGs are archiving RFCs locally in their repros which makes discovery hard. RFCs are also not being archived consistently. What processes should we be following? What should we be doing with https://github.com/o3de/rfcs? What should be the communication policy when RFCs are published, moved to final comment and accepted by a SIG?o

Action Items for SIG maintainers:
- Need to update issues templates for SIG. Meeting agenda template had SIG-BUILD as title. See https://github.com/o3de/sig-operations/blob/main/.github/ISSUE_TEMPLATE/Meeting-Agenda-Template.md and theres no standard maintainer promotion issue template ie https://github.com/o3de/sig-core/blob/main/.github/ISSUE_TEMPLATE/Reviewer_Maintainer_Nomination.md

**Comment by lmbr-pip** [comment]
Meeting occurred, notes archived. Closing issue.
